name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.3 # Dart SDK version
  flutter: ^3.10.3 # Flutter SDK version

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shake: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/sans.ttf

  uses-material-design: true
